
on: [ pull_request ]
jobs:
  runs-on: ubuntu-latest
  steps:
    - run: |
      echo "a=b" >> "$GITHUB_OUTPUT"
      echo "a=b" >> "$GITHUB_OUTPUT"
      echo $GITHUB_OUTPUT
      echo "ddasdasdasdasdafagWEG"
      cat $GITHUB_OUTPUT